DBUSERNAME= "supplier.io.dev"
SQLDATASOURCE= "issqldev.pc.factset.com"
DBTABLENAME= "Budget.workdaysupplierstaging"
PREFIXNAME= "SupplierPortal/WorkdaySuppliers/"
BUCKETNAME= "fdss3-supplier-portal-prod"
BUCKET_SIZE= 1
LAMBDA_NAME= "GetSuppliersFromWDFunction_PROD"
DBNAME="Supplier"
PASSWORDPATH="/supplierlist_process/supplier_db_password"